name: tanks
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  all_sensors2: ^1.0.1
  dio: ^5.3.0
  environment_sensors: ^0.3.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  get: ^4.6.5
  google_fonts: ^5.1.0
  meta: ^1.9.1
  mqtt_client: ^10.0.0
  sensors_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/loginlogo.png
