name: tanks
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  all_sensors2: ^1.0.1
  bloc: ^8.1.2
  dio: ^5.3.0
  environment_sensors: ^0.2.0
  firebase_database: ^10.2.4
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  meta: ^1.9.1
  provider: ^6.0.5
  sensors_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/image.png"
    background_color: "#fff"
    theme_color: "#fff"
  windows:
    generate: true
    image_path: "assets/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/image.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
